# Setup

# This file requires using the environment created from environment-gtfparse.yml

In [ ]:
# Imports

import polars as pl
import duckdb
from pathlib import Path
import math
import os
import numpy as np
from tqdm.notebook import tqdm

For this analysis you will need to obtain the COSMIC genome screening files as well as the COSMIC mutation classification file.
This analysis was based on the v99 release of COSMIC database
You can find the files and the license information at
https://cancer.sanger.ac.uk/cosmic/download/cosmic


Create a directory `COSMIC` inside the `data/subsidiary-files` folder and copy the Cosmic tsv files there.

In [ ]:
# Paths
project_dir = Path("/data/teamgdansk/mwaleron/carmen-analysis")

data_dir = project_dir.joinpath("data")
temp_dir = project_dir.joinpath("temp")

db_main_file = data_dir.joinpath("carmen-main.parquet")

data_subs_dir = data_dir.joinpath("subsidiary-files")
data_pub_dir = data_dir.joinpath("to-be-published")

cosmic_data_dir = data_subs_dir.joinpath("COSMIC")
cosmic_genome_screening_file = cosmic_data_dir.joinpath("Cosmic_GenomeScreensMutant_v99_GRCh38.tsv")
cosmic_classification_file = cosmic_data_dir.joinpath("Cosmic_Classification_v99_GRCh38.tsv")

braun_dataset_mut = data_subs_dir.joinpath("Braun_mutations_hg38_with_epitope_contigs.tsv")


gendode_data_dir = data_subs_dir.joinpath("GENCODE")
gencodev39_stripped = gendode_data_dir.joinpath("gencode.v39.annotation.stripped.versions.parquet")

contig_scaffold_list_file = data_pub_dir.joinpath("scaff_all_expanded.tsv")
contig_peptide_list_file = data_pub_dir.joinpath("contig_unique_peptide_list.tsv")
contig_hotspot_score_file = data_subs_dir.joinpath("sorted_normalized_contig_score.parquet")
contig_hotspot_score_top_quadrant_file = data_subs_dir.joinpath("contigs_top_quadrant_by_peptides_coverage.parquet")
pogo_mapping_filtered_by_top_quadrant_contigs = data_subs_dir.joinpath("pogo_tq.parquet")

exon_ranges_in_contigs_file = data_subs_dir.joinpath("evenbiggerjoin_cause_its_exons_not_just_genes_v2_just_the_contig_genes.parquet")

cosmic_somatics_overlap_with_contigs_file = data_subs_dir.joinpath("cosmic_somatics_overlap_with_contigs.parquet")
cosmic_somatics_overlap_with_top_quadrant_file = data_subs_dir.joinpath("cosmic_somatics_overlap_with_tq.parquet")
cosmic_mutations_in_contigs_semi_anti_file_B = data_subs_dir.joinpath("contig_cosmic_mutations.parquet")
cosmic_mutations_in_contigs_semi_anti_file_B_compliment = data_subs_dir.joinpath("non_contig_cosmic_mutations.parquet")
cosmic_mutations_in_top_quadrant_semi_anti_file_B = data_subs_dir.joinpath("tq_cosmic_mutations.parquet")
cosmic_mutations_in_top_quadrant_semi_anti_file_B_compliment = data_subs_dir.joinpath("non_tq_cosmic_mutations.parquet")

main_samples_file = data_dir.joinpath("main-output-table-1.tsv")
main_samples_file_2 = data_dir.joinpath("main-output-table-2.tsv")
main_samples_file_3 = data_subs_dir.joinpath("emilia_umap_with_ids.parquet")

In [6]:
cosmic_somatics = pl.read_csv(
    cosmic_genome_screening_file, 
    separator='\t')
cosmic_classification = pl.read_csv(
    cosmic_classification_file, 
    separator='\t')
contig_scaffold_list = pl.read_csv(
    contig_scaffold_list_file,
    separator='\t')
contig_peptide_list = pl.read_csv(
    contig_peptide_list_file, 
    separator='\t')

In [4]:
#exec disabled - just read the saved parquet
%%script false --no-raise-error

justcontigs = contig_scaffold_list.filter(pl.col("gap_width") == 0)
mutations_in_contigs = duckdb.sql('''
                                select *
                                from justcontigs j, cosmic_somatics_chr c
                                where (j.Chromosome = c.CHROMOSOME)
                                and(
                                    (c.GENOME_START between j.Gene_start and j.Gene_end)
                                or  (c.GENOME_STOP between j.Gene_Start and j.Gene_end)
                                )
                                ''')
mutations_in_contigs_res = mutations_in_contigs.pl()
mutations_in_contigs_res.write_parquet(cosmic_somatics_overlap_with_contigs_file)

UsageError: Line magic function `%%script` not found.

In [8]:
cosmic_mutcount_per_contig_tmp = temp_dir.joinpath("mutation_count_per_contig.parquet")

mutations_in_contigs_res = pl.read_parquet(cosmic_somatics_overlap_with_contigs_file)
mutation_count_per_contig = mutations_in_contigs_res\
                            .group_by("Id").len().sort("len")
mutation_count_per_contig_C_name =  contig_scaffold_list\
                                    .join(
                                       mutation_count_per_contig,
                                       on="Id",
                                       how="left")\
                                    .fill_null(0)\
                                    .filter(pl.col("gap_width") == 0)\
                                    .select(["Contigs", "len"])
mutation_sum_per_scaffold = contig_scaffold_list\
                            .join(
                                mutation_count_per_contig_C_name,
                                on="Contigs")\
                            .select(["Id", "len"])\
                            .group_by("Id").sum().sort("len")
mutation_sum_per_scaffold.filter(pl.col("Id").str.starts_with("S_0"))\
                         .write_parquet(cosmic_mutcount_per_contig_tmp)

/tmp/ipykernel_104810/2108381767.py:6: DeprecationWarning: The default coalesce behavior of left join will change to `False` in the next breaking release. Pass `coalesce=True` to keep the current behavior and silence this warning.
  mutation_count_per_contig_C_name =  contig_scaffold_list\

In [5]:
unique_peptides_per_contig_tmp = temp_dir.joinpath("unique_peptides_per_contig.parquet")
contig_peptide_one_to_one = contig_peptide_list\
                            .with_columns(pl.col("pep_list").str.split(','))\
                            .explode("pep_list")\
                            .unique(["pep_list", "contig"])\
                            .select(["pep_list", "contig"])
scaffold_peptide = contig_scaffold_list\
                   .join(
                       contig_peptide_one_to_one,
                       left_on="Contigs",
                       right_on="contig")\
                   .unique(["Id", "pep_list"])\
                   .group_by("Id").agg("pep_list")
emilia_umap = pl.read_csv(main_samples_file, separator="\t")
emilia_umap_peptides = pl.read_csv(main_samples_file_2, separator="\t")
emilia_umap_with_ids =  emilia_umap\
                        .with_row_index()\
                        .hstack(emilia_umap_peptides.select("Id", "Peptides"))\
                        .with_columns(Peptides = pl.col("Peptides").str.split(","))
emilia_umap_with_ids.write_parquet(main_samples_file_3)
unique_peptides_per_contig =    scaffold_peptide\
                                .with_columns(unique_peptides = pl.col("pep_list").list.len())\
                                .filter(pl.col("Id").str.starts_with("S_0"))
unique_peptides_per_contig.write_parquet(unique_peptides_per_contig_tmp)

calculation_spam_dir = temp_dir.joinpath("parquetspam")
calculation_spam_dir.mkdir(parents=True,exist_ok=True)
contig_peptide = scaffold_peptide.filter(pl.col("Id").str.starts_with("S_0"))
number_of_shards = math.ceil(len(contig_peptide)/10000)
for i in range(number_of_shards):
    contig_peptide.slice(10000*i, 10000)\
                  .write_parquet(calculation_spam_dir.joinpath(f"contig_slice_{i}.parquet"))

In [ ]:
# run the compute on the slices
# it is recommended to use parallel, SLURM or other parallelization method here,
# eg seq 0 1 {number_of_shards} | parallel --bar python ./calculate_immune_score.py
for i in range(number_of_shards):
    os.system(f"python ./calculate_immune_score.py {i}")

In [ ]:
contig_hotspot_score_file_tmp = temp_dir.joinpath("hotspot_score_3_axis_per_contig.parquet")
test=pl.read_parquet(calculation_spam_dir.joinpath("scored_contig_slice_*"))
popcov_per_contig_file_tmp = temp_dir.joinpath("population_coverage_per_contig.parquet")
test.write_parquet(popcov_per_contig_file_tmp)
mutation_sum_per_scaffold = pl.read_parquet(cosmic_mutcount_per_contig_tmp)
test.join(unique_peptides_per_contig, on="Id")\
    .join(mutation_sum_per_scaffold, on="Id")\
    .drop("pep_list", "pep_list_right")\
    .rename({"len":"mutation_count"})\
    .write_parquet(contig_hotspot_score_file_tmp)
exon_join=pl.scan_parquet(exon_ranges_in_contigs_file)
contig_exon_len = exon_join\
                    .filter(pl.col("gap_width")==0)\
                    .with_columns(exon_length = pl.col("exon_end") - pl.col("exon_start"))\
                    .select("Id", "exon_length")\
                    .group_by("Id").sum().collect()
hotspot_score_3_axis_per_contig = pl.read_parquet(contig_hotspot_score_file_tmp).join(contig_exon_len, on="Id")
hotspot_score_3_axis_per_contig =  hotspot_score_3_axis_per_contig\
                                   .with_columns(normalized_unique_pep = pl.col("unique_peptides") / pl.col("exon_length"))
hotspot_score_3_axis_per_contig = hotspot_score_3_axis_per_contig\
                                  .sort(pl.col("popcov_but_sqrt"), descending=True)\
                                  .with_row_index("pop_cov_idx")\
                                  .sort(pl.col("mutation_count"), descending=True)\
                                  .with_row_index("mut_count_idx")\
                                  .sort(pl.col("normalized_unique_pep"), descending=True)\
                                  .with_row_index("unique_pep_idx")\
                                  .with_columns(
                                      ranking= pl.col("unique_pep_idx") + pl.col("mut_count_idx") + pl.col("pop_cov_idx"))\
                                  .sort("ranking")
hotspot_score_3_axis_per_contig.write_parquet(contig_hotspot_score_file)
hotspot_score_3_axis_per_contig = pl.read_parquet(contig_hotspot_score_file)
hotspot_score_3_axis_per_contig.filter(
                                        pl.col("unique_pep_idx") < pl.col("unique_pep_idx").median() , 
                                        pl.col("popcov_but_sqrt") > 13)\
                                .write_parquet(contig_hotspot_score_top_quadrant_file)
top_quadrant = pl.read_parquet(contig_hotspot_score_top_quadrant_file)
justcontigs = contig_scaffold_list.filter(pl.col("gap_width") == 0, pl.col("Id").is_in(top_quadrant["Id"]))

In [9]:
pep_main=pl.read_parquet(db_main_file)

In [10]:
pep_main.head()

shape: (5, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Study_id  ┆ Sample_na ┆ Peptide   ┆ Peptide_t ┆ … ┆ Assigned_ ┆ Haplotype ┆ Netmhcpan ┆ Promiscu │
│ ---       ┆ me        ┆ ---       ┆ ype       ┆   ┆ modificat ┆ ---       ┆ _binder   ┆ ity      │
│ str       ┆ ---       ┆ str       ┆ ---       ┆   ┆ ions      ┆ str       ┆ ---       ┆ ---      │
│           ┆ str       ┆           ┆ str       ┆   ┆ ---       ┆           ┆ str       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ MSV000080 ┆ sample_A0 ┆ AADIFYSRY ┆ canonical ┆ … ┆ null      ┆ A*01:01   ┆ Y         ┆ 0.688129 │
│ 527-84172 ┆ 101       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ -84442    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MSV000080 ┆ sample_A0 ┆ AADLNLVLY ┆ canonical ┆ … ┆ null      ┆ A*01:01   ┆ Y         ┆ 8.672632 │
│ 527-84172 ┆ 101       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ -84442    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MSV000080 ┆ sample_A0 ┆ AADPNAAWA ┆ canonical ┆ … ┆ null      ┆ A*01:01   ┆ Y         ┆ 0.387766 │
│ 527-84172 ┆ 101       ┆ AY        ┆           ┆   ┆           ┆           ┆           ┆          │
│ -84442    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MSV000080 ┆ sample_A0 ┆ AADPNAAWA ┆ canonical ┆ … ┆ null      ┆ A*01:01   ┆ Y         ┆ 0.769507 │
│ 527-84172 ┆ 101       ┆ AYY       ┆           ┆   ┆           ┆           ┆           ┆          │
│ -84442    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MSV000080 ┆ sample_A0 ┆ AAEDIINYT ┆ canonical ┆ … ┆ null      ┆ A*01:01   ┆ Y         ┆ 0.0      │
│ 527-84172 ┆ 101       ┆ EPKLGY    ┆           ┆   ┆           ┆           ┆           ┆          │
│ -84442    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [4]:
emilia_umap_with_ids = pl.read_parquet(main_samples_file_3)
xallcen = (emilia_umap_with_ids["x"].min() + emilia_umap_with_ids["x"].max() )/2
yallcen = (emilia_umap_with_ids["y"].min() + emilia_umap_with_ids["y"].max() )/2

In [ ]:
def promiscuity_peptide_list(input):
    scorebase = emilia_umap_with_ids\
        .with_columns(
        scafres = pl.col("Peptides").list.set_intersection(input
        ))\
        .with_columns(alen = pl.col("scafres").list.len()).sort("alen")
    xy = scorebase.filter(pl.col("alen")>0).select("x","y")
    count = len(xy)
    if count == 0 :
        return 0
    xcen = xy["x"].sum()/count
    ycen = xy["y"].sum()/count
    lth = np.sqrt( np.power(xallcen-xcen,2) + np.power(yallcen-ycen,2))
    popcov_but_sqrt = count / math.sqrt(1+lth)
    return popcov_but_sqrt

In [8]:
czytoprom = []
for umap in tqdm(emilia_umap_with_ids.iter_rows(named=True)):
    czytoprom.append(promiscuity_peptide_list(umap["Peptides"]))
czytoprom

0it [00:00, ?it/s]

[883.910793639971,
 638.8008939022592,
 1208.9796874488784,
 945.3704822881189,
 591.9475192737682,
 895.8843034488854,
 550.8728102494181,
 772.4626799301442,
 670.5295974477691,
 617.9558094411568,
 628.1668716524906,
 632.1804377561988,
 662.5624153811046,
 1974.0232538263913,
 1703.895620620031,
 1641.8219069567078,
 468.3290065753511,
 1138.5123256200625,
 2061.9880471246347,
 1931.411066213954,
 7.63475327056367,
 95.75851286565667,
 93.27702599073969,
 71.35793895151963,
 609.0177556122259,
 938.5179595479666,
 831.9067609103312,
 1158.0623532695054,
 893.1525551940465,
 1072.8162584286072,
 299.4185396581656,
 528.9058693498288,
 448.28054261871443,
 453.3600989088737,
 166.13807502060672,
 297.08990550904423,
 178.8552876909029,
 23.91864794222972,
 261.7239203964983,
 0.5027194866830007,
 244.19528034279375,
 11.71903338828537,
 2585.478069653016,
 1026.7197779525225,
 952.9954111857886,
 989.1127152239825,
 333.97054464098505,
 1074.2112539400005,
 187.49308477489396,
 1060.4024396442226,
 1439.1866344436557,
 574.6391514924715,
 1056.2300355668579,
 1156.4217064267252,
 1640.501134941935,
 1117.6688395769456,
 914.3900455439607,
 1569.2069544916749,
 515.8507953229437,
 1316.9940476293773,
 1761.1992587835166,
 1196.9720212033121,
 2027.366987310511,
 681.3896584562833,
 971.3710024569458,
 3237.0843025315853,
 869.8085157146841,
 1774.317715035075,
 309.9629025193495,
 439.0695147702519,
 557.295192368795,
 115.03516459565135,
 811.387718114013,
 7.024397529023959,
 1672.4404247874857,
 1938.0985196328807,
 1282.98245880984,
 891.2639593220441,
 1292.6537710184136,
 835.983227571118,
 1046.9359014498598,
 1795.003254606796,
 2144.6712939138915,
 1000.6774750086489,
 1141.3971444964109,
 845.913293571413,
 1075.1081568526179,
 4.253425057267454,
 26.274180326850374,
 29.474283735590365,
 152.25345692719128,
 27.39336156649699,
 34.28099832282965,
 330.926543543478,
 430.2325284593742,
 472.5598673096361,
 1641.55119085088,
 991.8631010277974,
 1262.683260069058,
 1948.7954811893094,
 936.5455004346579,
 1046.5795577233,
 1551.2284726251096,
 1694.8877929413254,
 1262.412663622104,
 1254.2390396341254,
 388.07436661535456,
 578.8473490754368,
 8.4698062851299,
 184.7914629199087,
 246.96786364725273,
 294.26005420434865,
 26.254436783690142,
 82.4489924203569,
 115.2527152543577,
 85.62309699620164,
 67.23392883672634,
 2298.9646583477806,
 1575.290383053801,
 1239.2545355677503,
 4.253425057267454,
 26.274180326850374,
 2626.0920182466325,
 1493.7983214126623,
 1226.6179481689844,
 117.10298140179657,
 124.22521098962274,
 289.04002569423096,
 65.9909268099007,
 653.0727303076053,
 962.8500115246437,
 987.8916254158025,
 855.8503793647074,
 740.2565240697168,
 889.2292693398007,
 2327.5346423095903,
 1816.9746909872404,
 704.1368828808615,
 0.3742896695324567,
 2645.4803638592643,
 887.157919833929,
 940.1946759937586,
 1056.2933922212242,
 1457.0173270300727,
 2144.2967157140893,
 2146.8125177452766,
 1262.9896341222118,
 1265.2771702854852,
 1510.2302279986122,
 139.29303810367438,
 1050.9775747499093,
 648.9674290428236,
 1653.0174008371569,
 1378.6196633821855,
 809.7477259164257,
 422.990531141098,
 772.2746255700339,
 1146.9489093763887,
 1262.2960444149091,
 1122.9747168045649,
 1965.3243120831407,
 2495.407313256651,
 359.7370658268454,
 448.0961619914561,
 559.2049576463534,
 2054.403274236588,
 832.1557213931667,
 1594.7088451741436,
 560.1967783384155,
 306.98317383868795,
 135.08490467812948,
 135.90522082377672,
 1088.408398483843,
 2489.3533242034523,
 1573.5038925252375,
 943.6189487123077,
 1409.3080524717473,
 461.992705863802,
 425.74959144275294,
 334.66116623191533,
 901.436747651809,
 787.9480145823794,
 28.644816897554332,
 323.77326493631995,
 381.04755230667297,
 1952.151503523597,
 1416.7103334141746,
 1163.4559723809032,
 1533.0770523371611,
 1313.6638383702496,
 898.8213321884599,
 1804.088781045627,
 1255.772655027037,
 1224.5351217301277,
 1017.5284144317951,
 722.274354918639,
 32.122334283788355,
 172.21452673997243,
 609.1137980477691,
 2866.457131954482,
 2034.4573291347235,
 1555.902575693398,
 1134.3486275793703,
 759.5437417533994,
 1165.4790026195274,
 2557.0751242748215,
 3.0952458693284157,
 17.60428914957555,
 2234.274847620458,
 2524.7963735995677,
 1597.8308646738706,
 463.24579546631975,
 10.407933705767855,
 595.941072278208,
 496.1964701848795,
 645.2810652266636,
 586.9673496809196,
 357.7080112592984,
 1747.0229115174102,
 1002.8888766911117,
 1653.0031901921861,
 2273.864482972866,
 1950.9019238161266,
 1411.1678752491434,
 843.5543965021845,
 772.6558401879801,
 1055.0896988285576,
 426.61554026127203,
 808.8387215305311,
 1076.2164918480105,
 2064.4026205468117,
 1599.0856132120948,
 1289.2371796630418,
 1220.808664211428,
 1430.076983473339,
 603.4743614612277,
 2288.6093188751306,
 942.3506791155257,
 2511.697023863314,
 877.7662448621563,
 804.2018195267501,
 596.459539753179,
 1096.1765126307823,
 655.3587988953419,
 723.5647405702623,
 179.96184477427443,
 330.5278024653846,
 866.5442313802135,
 437.41814677505306,
 484.77728491867157,
 681.520737265869,
 1601.7445924747133,
 877.1492882226495,
 1267.9143401572142,
 148.08841330239457,
 208.77827543557595,
 749.2411111226742,
 453.44589941491597,
 303.70439130551176,
 886.3403300214551,
 808.0860666285315,
 936.2268612631694,
 818.4422729581327,
 1408.9466255783602,
 1981.9702531476682,
 3071.6739524094874,
 796.9355767973818,
 884.5976259628186,
 1195.9970945359896,
 295.76390404993487,
 733.4286281538404,
 377.13326186525967,
 616.392773536747,
 1314.7071974648463,
 554.0909528030834,
 94.91771126195164,
 298.3257821131944,
 0.6364108851140916,
 688.1630126486061,
 26.63703068904943,
 546.1796739810626,
 1095.949625479756,
 439.2294174403507,
 847.2547624561091,
 2195.0951669065166,
 1640.563963350534,
 830.232436617005,
 191.51778932168773,
 438.15881739111734,
 232.24097728368898,
 514.685304462421,
 255.81342442026528,
 3.0952458693284157,
 1154.7289751847804,
 897.4946782592933,
 1278.995378874823,
 460.2857597107392,
 399.9485543316323,
 643.6613326922998,
 2410.181853275446,
 1069.0611467873973,
 1927.1470685673578,
 1304.7595689791474,
 1280.1892804801525,
 1519.8629683696245,
 20.391573438363555,
 691.833100417562,
 146.0600696999034,
 496.13953942429924,
 523.6788823322443,
 52.72885684184294,
 1448.1711325322915,
 1291.4480812987156,
 1084.4247014588286,
 959.3341688639874,
 986.2798001652803,
 37.96195853216041,
 887.7698265824923,
 171.61474036891468,
 354.08497758533605,
 172.80795753927453,
 38.65664745900282,
 673.237487072558,
 881.306539293713,
 595.321957801436,
 1118.519846249229,
 1143.301490395255,
 1997.198109640478,
 513.3304234572579,
 693.9846223604889,
 529.9736175018926,
 667.9932358877411,
 703.7390374437747,
 484.42139346808085,
 981.9334352787828,
 1332.1173709165562,
 845.6513567911129,
 1498.849087161251,
 866.1497965733564,
 1556.00989184625,
 763.6725138321183,
 1412.8480721663152,
 1807.58710663521,
 832.8941901472009,
 777.8355072327763,
 831.424889949142,
 12.835478297763146,
 551.038751374426,
 678.9547369196921,
 1537.7701287740883,
 939.7570990475431,
 559.8569197189271,
 1379.2507921096553,
 1159.1155789974598,
 60.6374850352956,
 1.3145955420555138,
 131.11941426717857,
 227.1100976541821,
 522.8766527463762,
 426.60292294610196,
 190.37098629301994,
 1969.8605923573643,
 810.5571640945649,
 1334.0717532141093,
 1357.3546308040943,
 2100.7911959752637,
 1174.2827372890188,
 571.6231380742629,
 564.6131573027837,
 862.6076275897022,
 813.6698505501081,
 616.0710139171435,
 626.6764048444901,
 1174.0491356180942,
 799.5408519076982,
 906.752070971297,
 645.2287487324406,
 826.0871955134968,
 946.9678893371259,
 1512.0643924618148,
 235.895633560941,
 208.30937842265348,
 242.3137108797959,
 1756.5042239467703,
 1240.1526534984887,
 1274.8825194251292,
 455.63696609671666,
 1308.3461518291324,
 47.193937435885594,
 240.10312669331591,
 766.0073169450861,
 1724.6746349518671,
 1968.4818677357632,
 1842.9764950644205,
 3.961506961000325,
 3030.6467623508984,
 1334.7812501846875,
 847.9038578872331,
 1934.3383279872062,
 1620.3516461053764,
 1371.9517881073837,
 1007.7225580276549,
 758.4446143027045,
 815.0958344478997,
 709.7575147177148,
 10.427193644354013,
 1125.8067305092657,
 714.8007976836637,
 1146.4455339983044,
 1425.8586117941215,
 420.4159736193967,
 813.4962229066591,
 917.0452670306421,
 1222.475175187148,
 1311.6527010094055,
 1907.5285616773874,
 2028.3827397431075,
 1600.9743933661998,
 636.6246819694275,
 784.2839451933122,
 777.4152944422409,
 376.9625315764565,
 264.0982805351776,
 688.1812497327862,
 2386.208979201279,
 976.6392483010651,
 1366.4796357316864,
 1044.0352863751546,
 2189.2884674693473,
 1351.7717964637413,
 1613.3741860187527,
 1494.7911319357424,
 646.3634136830415,
 770.0007837978426,
 385.55461169380607,
 829.4684663792427,
 1407.4124756603421,
 1711.8762563648586,
 6.147186987699036,
 1741.9821731909803,
 2126.985667711211,
 1617.3299783162481,
 1178.1400990938162,
 511.74771615239763,
 673.806684967765,
 1610.697036109182,
 171.02268394264058,
 243.59421145640403,
 145.2817644118885,
 421.1237493356872,
 913.0961919721996,
 437.57652129674966,
 1062.6515301026711,
 814.7747053133531,
 1697.7112112284515,
 1401.2225221615165,
 803.2836833134844,
 201.83380455677306,
 973.6530259459572,
 1007.0532086322046,
 2129.892503360088,
 24.49221329986556,
 61.0056226506372,
 51.94381429557242,
 976.1122414228615,
 1048.6321547813714,
 2044.042936160025,
 409.37527302533476,
 525.3222994071596,
 451.15651594835765,
 443.3572247372602,
 3044.8188660560704,
 1071.8351724966788,
 1178.0033723133884,
 116.14107735009195,
 1203.5449386305083,
 1199.7937633369056,
 2259.785326280035,
 712.0814324645783,
 850.0601805098125,
 1723.1055097821366,
 1033.4856480788942,
 688.6247537545603,
 1992.9745879186091,
 530.1674668983615,
 184.19246106753968,
 1832.8727936597734,
 2028.9094910986978,
 1072.773039658231,
 1322.2261092972913,
 402.0099467635407,
 677.935052242544,
 551.8451156238532,
 771.2092174510311,
 1578.101858560578,
 2148.7216199475547,
 1089.5572493568675,
 653.9453130671135,
 392.2946516101503,
 1201.5245671299544,
 1285.1745412235452,
 1438.6912943550922,
 1003.9290889250841,
 784.124948040751,
 994.0969272990488,
 1842.9871154519042,
 898.2555253444076,
 451.64621565085866,
 149.01474953153908,
 583.3824181379534,
 968.1719448121165,
 653.0400349061938,
 2405.1335104194754,
 1844.160044600754,
 734.1121156482686,
 390.8797639723962,
 421.0212841601707,
 827.8004768045471,
 805.4488917240213,
 1532.5525636912982,
 1063.2357867983005,
 943.1790885345065,
 1251.7962389709396,
 752.4250190617988,
 1722.9770122276466,
 1496.0034095674755,
 1265.2194046012348,
 1995.591937879892,
 1669.6842075884836,
 335.137197812683,
 469.61034399191084,
 573.033766052343,
 689.8320063967866,
 736.7999831137437,
 757.2871603283672,
 995.4099691074165,
 1744.274438956579,
 1088.867022614595,
 878.8229171516364,
 1013.233018044613,
 1231.1763116028164,
 1553.11714821195,
 1152.521980259213,
 202.2160336545986,
 491.4981545905497,
 132.7155132439703,
 1283.7564976073882,
 919.6864970586748,
 1788.0610830035857,
 1754.8022718698446,
 2080.018736768917,
 2256.0069052731365,
 596.1757742879137,
 520.9254806422441,
 1469.040470859739,
 1469.1599780615297,
 714.1275849681197,
 2479.6628415160076,
 2373.748619724276,
 822.8315352865873,
 1964.3512177142427,
 325.76197294388993,
 16.80818614969097,
 202.3401049716552,
 1505.81885638661,
 814.4948763805836,
 2121.333668544004,
 1134.6098805645288,
 1248.0480554477645,
 1992.5953099085389,
 2051.9281183680746,
 911.8638867757277,
 1233.9730953395792,
 1268.2316188088457,
 1484.6158999477482,
 773.1003539601811,
 1786.1184701123077,
 730.3508362656474,
 184.46958329789587,
 14.544022407825198,
 86.98774013835302,
 930.6737409018866,
 676.7190668034629,
 1336.8786404730065,
 73.449126359192,
 1657.990009980814,
 891.8521813018123,
 1633.505613242738,
 1722.9650071823405,
 982.2053402072913,
 1112.9664538234622,
 923.9068036118226,
 1009.8642719943922,
 1244.8822295284438,
 1468.0031345772863,
 2142.664591314156,
 415.19674003796314,
 573.5152472690257,
 595.93151216276,
 117.83900604131455,
 100.89767447860133,
 92.19674190502678,
 1340.805138173271,
 1091.4803459218792,
 985.3633743266575,
 1547.555521703491,
 1259.8102045928435,
 1184.206666068373,
 1135.6796529300332,
 703.9339596805463,
 1912.1443063539514,
 1839.7478689800257,
 1943.863796935963,
 517.0541100084324,
 2329.455481794866,
 1184.095937066594,
 434.8582421397859,
 1175.903791378615,
 639.2254572726972,
 1493.9902101581142,
 2578.3190460249903,
 1957.5419116500282,
 4.182812184573377,
 7.144296227877199,
 2.179499864239214,
 1104.8703476657033,
 1233.6084505013055,
 806.9565631793116,
 108.16364595791539,
 608.9664847757084,
 759.0538037140897,
 1247.0671007216376,
 1086.7351880915724,
 2.325521900693736,
 1939.0130389463063,
 2274.491668046843,
 1846.5542909476633,
 1071.6727424463234,
 1165.8655332620472,
 1910.9753483488826,
 2214.2517650903683,
 695.37581172733,
 1856.6159655123176,
 295.7638841843049,
 1313.4890169221594,
 29.082241174157414,
 616.0679441630991,
 670.7254647918656,
 548.4576001238213,
 350.17840214303186,
 1404.0301195599466,
 827.662552090177,
 964.8676988236233,
 1457.06909171344,
 1041.5996536211035,
 1037.1430067358185,
 2147.148289562357,
 2401.011210765505,
 1881.2803143279973,
 827.0132465066056,
 1131.1012625428314,
 1513.4360389526953,
 559.1035907052465,
 742.4678632794913,
 1663.4239123066855,
 1124.3415788448476,
 1935.4537940363061,
 2465.807363615598,
 2031.0383771815193,
 1759.5090141849018,
 785.7745880626175,
 1044.3528614293982,
 1282.6382334261934,
 623.1151083240882,
 2202.2630176067005,
 1787.8343841806955,
 1335.4566927934793,
 915.9343372499189,
 2192.335076907266,
 825.0031492403056,
 1856.5556772031746,
 851.572318067084,
 1721.8923430523075,
 933.6172163913257,
 3103.48444468536,
 2015.9527159537574,
 1244.3722581364352,
 1402.780395711208,
 1805.2337641958668,
 1485.9545061522351,
 3034.2167752264318,
 1070.5342966445835,
 2611.723863780224,
 1553.7691577072721,
 1416.5851568586488,
 610.9470426707555,
 420.1348488389864,
 915.4236076415492,
 65.81560621431244,
 131.90415438224048,
 39.231427567934404,
 90.31824044432115,
 92.94956817085273,
 163.48394937971173,
 1374.9624978369409,
 1470.5941687355305,
 1223.1486335460154,
 523.1130716867763,
 544.2847677765094,
 465.01035041297075,
 576.3443518660879,
 584.9404572354375,
 805.1880857417382,
 1305.1605996769347,
 2049.9091139687375,
 2467.568990275979,
 519.1027339509296,
 915.2218653437297,
 493.4047637193142,
 258.9505219909204,
 699.0237461806904,
 730.25349656859,
 761.1146936638639,
 649.6672820099692,
 1144.1631326966806,
 1022.7404918907506,
 1235.2693358163963,
 856.3325605438002,
 1478.0038452741821,
 1419.1403094724683,
 2149.6402040574267,
 1089.7775224738853,
 798.1551455160854,
 844.6311862507555,
 775.3405705551094,
 1753.4463325032311,
 1432.2577997051421,
 981.9879170446331,
 1102.7167975491266,
 880.7712414688946,
 2389.2152745595376,
 887.4534988282226,
 1500.3830721078325,
 1792.2933881567405,
 2238.890976587506,
 263.19746343425226,
 562.2280252921641,
 27.426588154062937,
 137.2085985995512,
 85.81065742471733,
 149.6446604529798,
 1269.0986798321208,
 579.164967931283,
 697.3540830341042,
 1464.7886102525906,
 818.8545726185652,
 1142.5137059574874,
 348.49638013404035,
 548.5037453925796,
 712.1455074405594,
 541.5766766245802,
 88.62895683236385,
 318.62944731254896,
 361.1750183504975,
 1033.4683336194164,
 339.5427126315969,
 2047.469218802541,
 11.787599886736231,
 50.14786531663157,
 34.11591863916635,
 7.031877365380365,
 31.3936311338833,
 24.870126739243222,
 455.7797737169272,
 450.38058432723994,
 945.4452568996704,
 781.1909277141045,
 1338.5524564060338,
 1819.9160372138633,
 1597.3151703163505,
 804.9055720940078,
 1869.3699425635448,
 1141.5298610675402,
 17.32943661961054,
 198.44597868695388,
 993.2125163189932,
 53.72177403830621,
 654.2227676317428,
 758.2105634423364,
 692.7077766268554,
 830.7181498516397,
 1983.1964820140995,
 758.3503555443218,
 1280.7070483639939,
 1289.0345981580856,
 1085.4379852989812,
 2291.76391852125,
 999.9954829627009,
 2520.9735987466674,
 2887.1329640333643,
 1941.9585160966687,
 2821.588553861124,
 1894.1545421089072,
 2525.541891928383,
 910.3042563722375,
 1865.1136742028236,
 1202.397362674052,
 575.4451446427324,
 1859.115040944017,
 1815.2456797414904,
 1528.8828830807356,
 1482.8460107690412,
 679.995152982362,
 2664.82992953192,
 1591.6767976729545,
 882.9634924963041,
 1773.781201233022,
 182.13004683169675,
 1055.8443504574534,
 293.48678506076305,
 594.0844888172115,
 1680.925122508015,
 1561.6771151415894,
 1090.2884051766712,
 1064.8752397625904,
 1917.2537707152756,
 592.7575107411549,
 1410.3571527719319,
 1907.3497972731261,
 1201.9238683826068,
 1774.2466781638007,
 752.2894911428226,
 1318.055649251282,
 1783.1222973441488,
 17.154022289202448,
 1528.863563945943,
 191.00207562505358,
 359.62086900636154,
 981.389334659289,
 522.280211470605,
 475.62360352922076,
 657.6843836652158,
 1060.5793457562581,
 1461.7030797579237,
 2471.4785733161,
 777.7972879407978,
 712.4918005558453,
 583.6119046495996,
 567.9629073293929,
 1406.8311636399835,
 620.6786427194709,
 1496.6588208342916,
 2341.8216468067512,
 1014.3579469599184,
 1371.9585941452387,
 1010.4332137580266,
 726.7407121217358,
 386.446668523759,
 1923.6253108602407,
 1011.8747369647424,
 599.2508713460591,
 346.19155965329116,
 605.2912391494898,
 1397.3198006475036,
 674.1973955991274,
 891.6596727477692,
 2043.2110890797353,
 1593.696926781317,
 980.5264480929523,
 2022.9989594009105,
 2115.40593813621,
 2964.71645972657,
 2439.3733746551525,
 1363.184869773458,
 893.9495395146064,
 861.0067467897777,
 3.469699633159087,
 6.617376488736282,
 11.165773029742807,
 38.40552049310453,
 215.20881772147138,
 21.04529431289109,
 2405.605349762286,
 1588.5432987133565,
 1283.320635744105,
 1922.0681530006252,
 695.0027784146232,
 2259.9165399325816,
 1467.0764938727648,
 877.7236602483102,
 424.4556031499863,
 436.7480211896555,
 266.28064723152494,
 744.226455329846,
 1818.79181259299,
 2405.9726616462126,
 1267.12530860872,
 218.37843142880806,
 302.97606859304125,
 166.79504772046215,
 881.4887303888462,
 720.4870373185412,
 1123.5963822383505,
 453.8196538943954,
 540.653696928727,
 928.4315719452434,
 45.836296250451596,
 1064.2523144763786,
 1010.2910980280606,
 2310.8801173732845,
 916.7484704976954,
 1038.446840304077,
 659.4138461212128,
 638.1019442344316,
 368.85309094380113,
 697.8314423385165,
 349.26781551945777,
 1557.2746487009726,
 1467.9475553455986,
 400.448404408869,
 1511.6846555950315,
 1101.2227591886733,
 1429.5292444953873,
 1019.3333259828667,
 243.39844230680185,
 1796.9111442265405,
 1358.546154020979,
 2262.5678932682526,
 1740.310067174898,
 639.413746745078,
 711.5458256980444,
 595.4762202517358,
 547.4963963848602,
 1061.148206842822,
 412.1667371594016,
 651.3829001364323,
 649.3776862530859,
 913.7705596459473,
 311.7734634742884,
 728.099273502302,
 530.741917739691,
 664.7845301423388,
 1225.1274786175914,
 508.1721287843074,
 1022.1947360395558,
 507.4376593085157,
 529.2328465350465,
 835.7896413669389,
 3.8174515392967505,
 12.250726546417033,
 1362.3676381640953,
 803.1444173551058,
 1606.5995645859025,
 64.51719577053096,
 926.3692084241851,
 1043.6206174839128,
 1092.19515078813,
 381.5246933256007,
 728.3253567057516,
 1316.8717476906022,
 1352.4382782544583,
 1895.6352525838727,
 1196.5367536374251,
 1776.25933593902,
 1326.8733996113338,
 1185.297032505257,
 1244.9215051879924,
 2112.320205212178,
 1006.3438844756422,
 1646.4317226148025,
 1362.6601890591555,
 1287.9671647085254,
 555.3422216615027,
 452.44350635408074,
 433.8878296169659,
 118.15444297674651,
 137.2458999154482,
 76.8646958852862,
 96.62032863132079,
 464.52945787123264,
 641.6510209637415,

In [9]:
sample_prom = emilia_umap_with_ids.hstack(pl.DataFrame({"Promiscuity":czytoprom}))

In [10]:
sample_prom

shape: (5_693, 9)
┌───────┬──────────────┬─────────────┬───────────┬───┬───────┬─────────┬─────────────┬─────────────┐
│ index ┆ Sample       ┆ Binding_all ┆ x         ┆ … ┆ label ┆ Id      ┆ Peptides    ┆ Promiscuity │
│ ---   ┆ ---          ┆ eles        ┆ ---       ┆   ┆ ---   ┆ ---     ┆ ---         ┆ ---         │
│ u32   ┆ str          ┆ ---         ┆ f64       ┆   ┆ i64   ┆ str     ┆ list[str]   ┆ f64         │
│       ┆              ┆ str         ┆           ┆   ┆       ┆         ┆             ┆             │
╞═══════╪══════════════╪═════════════╪═══════════╪═══╪═══════╪═════════╪═════════════╪═════════════╡
│ 0     ┆ sample_PXD02 ┆ A*02:01,A*2 ┆ 0.191533  ┆ … ┆ 3     ┆ GC_0    ┆ ["AAMPRPVSY ┆ 883.910794  │
│       ┆ 7182_NB8_PAS ┆ 4:02,B*51:0 ┆           ┆   ┆       ┆         ┆ ", "AAYGRSP ┆             │
│       ┆ EGA_0B…      ┆ 1:01,B*5…   ┆           ┆   ┆       ┆         ┆ MV", … "…   ┆             │
│ 1     ┆ sample_PXD02 ┆ A*02:01,A*2 ┆ -1.854416 ┆ … ┆ 13    ┆ GC_1    ┆ ["AYASQFGTF ┆ 638.800894  │
│       ┆ 7182_NB8_PAS ┆ 4:02,B*51:0 ┆           ┆   ┆       ┆         ┆ ", "AYGSLFN ┆             │
│       ┆ EGA_0B…      ┆ 1:01,B*5…   ┆           ┆   ┆       ┆         ┆ TI", … "…   ┆             │
│ 2     ┆ sample_PXD02 ┆ A*02:01,A*2 ┆ 5.087642  ┆ … ┆ 6     ┆ GC_2    ┆ ["ALPPVLTTV ┆ 1208.979687 │
│       ┆ 7182_NB8_PAS ┆ 4:02,B*51:0 ┆           ┆   ┆       ┆         ┆ ", "DPPPGSH ┆             │
│       ┆ EGA_0B…      ┆ 1:01,B*5…   ┆           ┆   ┆       ┆         ┆ VI", … "…   ┆             │
│ 3     ┆ sample_PXD02 ┆ A*02:01,A*2 ┆ -1.499036 ┆ … ┆ 10    ┆ GC_3    ┆ ["AIVDKVPSV ┆ 945.370482  │
│       ┆ 7182_NB8_PAS ┆ 4:02,B*51:0 ┆           ┆   ┆       ┆         ┆ ", "ALADGVQ ┆             │
│       ┆ EGA_0B…      ┆ 1:01,B*5…   ┆           ┆   ┆       ┆         ┆ KV", … "…   ┆             │
│ 4     ┆ sample_PXD02 ┆ A*02:01,A*2 ┆ 4.7801905 ┆ … ┆ 6     ┆ GC_4    ┆ ["DAAAKALRI ┆ 591.947519  │
│       ┆ 7182_NB8_PAS ┆ 4:02,B*51:0 ┆           ┆   ┆       ┆         ┆ ", "DAAEFAI ┆             │
│       ┆ EGA_0B…      ┆ 1:01,B*5…   ┆           ┆   ┆       ┆         ┆ SI", … "…   ┆             │
│ …     ┆ …            ┆ …           ┆ …         ┆ … ┆ …     ┆ …       ┆ …           ┆ …           │
│ 5688  ┆ sample_20200 ┆ null        ┆ 5.4869995 ┆ … ┆ 0     ┆ GC_5688 ┆ ["AEEYEFLTP ┆ 56.588294   │
│       ┆ 513_COL015_0 ┆             ┆           ┆   ┆       ┆         ┆ VEEAPK",    ┆             │
│       ┆ 0007a_…      ┆             ┆           ┆   ┆       ┆         ┆ "ALQHMTDFA… ┆             │
│ 5689  ┆ sample_20200 ┆ null        ┆ 5.382379  ┆ … ┆ 0     ┆ GC_5689 ┆ ["AAAFEEQEN ┆ 107.256242  │
│       ┆ 513_COL015_0 ┆             ┆           ┆   ┆       ┆         ┆ ETVVVK",    ┆             │
│       ┆ 0007a_…      ┆             ┆           ┆   ┆       ┆         ┆ "AALSASEGE… ┆             │
│ 5690  ┆ sample_20200 ┆ null        ┆ 5.620569  ┆ … ┆ 0     ┆ GC_5690 ┆ ["AGVNVEPFW ┆ 32.488022   │
│       ┆ 513_COL015_0 ┆             ┆           ┆   ┆       ┆         ┆ PGLFAK",    ┆             │
│       ┆ 0007a_…      ┆             ┆           ┆   ┆       ┆         ┆ "AYSNWPTYP… ┆             │
│ 5691  ┆ sample_20200 ┆ null        ┆ 6.224224  ┆ … ┆ 0     ┆ GC_5691 ┆ ["AAEWQLDQP ┆ 68.626579   │
│       ┆ 513_COL015_0 ┆             ┆           ┆   ┆       ┆         ┆ SWSGR", "AE ┆             │
│       ┆ 0007a_…      ┆             ┆           ┆   ┆       ┆         ┆ QLGAEGNV…   ┆             │
│ 5692  ┆ sample_20200 ┆ null        ┆ 6.794512  ┆ … ┆ 6     ┆ GC_5692 ┆ ["APEDAGPQP ┆ 35.478164   │
│       ┆ 513_COL015_0 ┆             ┆           ┆   ┆       ┆         ┆ GSYEIR",    ┆             │
│       ┆ 0007a_…      ┆             ┆           ┆   ┆       ┆         ┆ "AWDQEAEGA… ┆             │
└───────┴──────────────┴─────────────┴───────────┴───┴───────┴─────────┴─────────────┴─────────────┘

# Top quadrant set generation

In [25]:
tq_peptides = top_quadrant.join(contig_scaffold_list, on="Id").join(contig_peptide_list, left_on="Contigs", right_on="contig").with_columns(pl.col("pep_list").str.split(",")).explode("pep_list").select(pl.col("pep_list").unique())

In [16]:

pogo_annotations_file = data_dir.joinpath("carmen-mapped-protein-annotations-pogo.parquet")

In [27]:
pl.read_parquet(pogo_annotations_file).filter(pl.col("Peptide").is_in(tq_peptides["pep_list"])).write_parquet(pogo_mapping_filtered_by_top_quadrant_contigs)

In [15]:
pl.read_parquet(pogo_mapping_filtered_by_top_quadrant_contigs)

shape: (1_936_129, 10)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬──────────┬────────┐
│ Peptide    ┆ Protein_id ┆ Transcript ┆ Gene_id   ┆ … ┆ Chromosom ┆ Gene_star ┆ Gene_end ┆ Strand │
│ ---        ┆ ---        ┆ _id        ┆ ---       ┆   ┆ e         ┆ t         ┆ ---      ┆ ---    │
│ str        ┆ str        ┆ ---        ┆ str       ┆   ┆ ---       ┆ ---       ┆ i64      ┆ str    │
│            ┆            ┆ str        ┆           ┆   ┆ str       ┆ i64       ┆          ┆        │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪════════╡
│ STFEDPQRLY ┆ ENSP000004 ┆ ENST000004 ┆ ENSG00000 ┆ … ┆ 1         ┆ 939360    ┆ 939390   ┆ +      │
│            ┆ 12228      ┆ 55979      ┆ 187634    ┆   ┆           ┆           ┆          ┆        │
│ STFEDPQRLY ┆ ENSP000003 ┆ ENST000003 ┆ ENSG00000 ┆ … ┆ 1         ┆ 939360    ┆ 939390   ┆ +      │
│            ┆ 49216      ┆ 41065      ┆ 187634    ┆   ┆           ┆           ┆          ┆        │
│ STFEDPQRLY ┆ ENSP000004 ┆ ENST000006 ┆ ENSG00000 ┆ … ┆ 1         ┆ 939360    ┆ 939390   ┆ +      │
│            ┆ 80870      ┆ 18181      ┆ 187634    ┆   ┆           ┆           ┆          ┆        │
│ STFEDPQRLY ┆ ENSP000003 ┆ ENST000003 ┆ ENSG00000 ┆ … ┆ 1         ┆ 939360    ┆ 939390   ┆ +      │
│            ┆ 42313      ┆ 42066      ┆ 187634    ┆   ┆           ┆           ┆          ┆        │
│ STFEDPQRLY ┆ ENSP000004 ┆ ENST000006 ┆ ENSG00000 ┆ … ┆ 1         ┆ 939360    ┆ 939390   ┆ +      │
│            ┆ 82090      ┆ 17307      ┆ 187634    ┆   ┆           ┆           ┆          ┆        │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …      │
│ IRQAGGIGK  ┆ null       ┆ null       ┆ null      ┆ … ┆ Y         ┆ 57210701  ┆ 57210728 ┆ +      │
│ RQAGGIGK   ┆ null       ┆ null       ┆ null      ┆ … ┆ Y         ┆ 57210704  ┆ 57210728 ┆ +      │
│ HLMSDLFNK  ┆ null       ┆ null       ┆ null      ┆ … ┆ Y         ┆ 57211574  ┆ 57211601 ┆ +      │
│ LMSDLFNKL  ┆ null       ┆ null       ┆ null      ┆ … ┆ Y         ┆ 57211577  ┆ 57211604 ┆ +      │
│ DLFNKLVMR  ┆ null       ┆ null       ┆ null      ┆ … ┆ Y         ┆ 57211586  ┆ 57211613 ┆ +      │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴──────────┴────────┘

In [ ]:
#exec disabled - just read the saved parquet
%%script false --no-raise-error

cosmic_somatics_chr = pl.read_csv(
    cosmic_genome_screening_file, 
    separator='\t').with_columns(CHROMOSOME = pl.lit("chr")+pl.col("CHROMOSOME").str.replace("MT","M"))
justtq = contig_scaffold_list.filter(pl.col("gap_width") == 0, pl.col("Id").is_in(top_quadrant["Id"]))
mutations_in_tq = duckdb.sql('''
                                select *
                                from justtq j, cosmic_somatics_chr c
                                where (j.Chromosome = c.CHROMOSOME)
                                and(
                                    (c.GENOME_START between j.Gene_start and j.Gene_end)
                                or  (c.GENOME_STOP between j.Gene_Start and j.Gene_end)
                                )
                                ''')
mutations_in_tq_res = mutations_in_tq.pl()
mutations_in_tq_res.write_parquet(cosmic_somatics_overlap_with_top_quadrant_file)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [ ]:
# This is the correct set in the sense mutations aren't doubled 
# Thus this one will be used for statistics
%%script false --no-raise-error
setB = cosmic_somatics.with_columns(
    CHROMOSOME=pl.col("CHROMOSOME").str.replace("MT","M")
    ).rename({"CHROMOSOME":"CHROMOSOME_1"}
             ).join(
                mutations_in_contigs_res.with_columns(
                    CHROMOSOME_1=pl.col("CHROMOSOME_1").str.strip_chars_start("chr")), 
                on=["GENOME_START","GENOME_STOP","CHROMOSOME_1"], 
                how="semi").collect()
setB.write_parquet(cosmic_mutations_in_contigs_semi_anti_file_B)

In [ ]:
# This is complimentary to setB
# ye just read the parquet as usual
%%script false --no-raise-error
non_contig_mutations = cosmic_somatics.with_columns(
    CHROMOSOME=pl.col("CHROMOSOME").str.replace("MT","M")
    ).rename({"CHROMOSOME":"CHROMOSOME_1"}
             ).join(
                mutations_in_contigs_res.with_columns(
                    CHROMOSOME_1=pl.col("CHROMOSOME_1").str.strip_chars_start("chr")), 
                on=["GENOME_START","GENOME_STOP","CHROMOSOME_1"], 
                how="anti").collect()

non_contig_mutations.write_parquet(cosmic_mutations_in_contigs_semi_anti_file_B_compliment)

In [ ]:
mutations_in_tq_res = pl.read_parquet(cosmic_somatics_overlap_with_top_quadrant_file)

In [ ]:
setB = pl.read_parquet(cosmic_mutations_in_contigs_semi_anti_file_B)

In [ ]:
non_contig_mutations = pl.read_parquet(cosmic_mutations_in_contigs_semi_anti_file_B_compliment)

In [12]:
setBtq = cosmic_somatics.with_columns(
    CHROMOSOME=pl.col("CHROMOSOME").str.replace("MT","M")
    ).rename({"CHROMOSOME":"CHROMOSOME_1"}
             ).join(
                mutations_in_tq_res.with_columns(
                    CHROMOSOME_1=pl.col("CHROMOSOME_1").str.strip_chars_start("chr")), 
                on=["GENOME_START","GENOME_STOP","CHROMOSOME_1"], 
                how="semi")
setBtq.write_parquet(cosmic_mutations_in_top_quadrant_semi_anti_file_B)
setBtq = pl.read_parquet(cosmic_mutations_in_top_quadrant_semi_anti_file_B)

non_tq_mutations = cosmic_somatics.with_columns(
    CHROMOSOME=pl.col("CHROMOSOME").str.replace("MT","M")
    ).rename({"CHROMOSOME":"CHROMOSOME_1"}
             ).join(
                mutations_in_tq_res.with_columns(
                    CHROMOSOME_1=pl.col("CHROMOSOME_1").str.strip_chars_start("chr")), 
                on=["GENOME_START","GENOME_STOP","CHROMOSOME_1"], 
                how="anti")

non_tq_mutations.write_parquet(cosmic_mutations_in_top_quadrant_semi_anti_file_B_compliment)
non_tq_mutations = pl.read_parquet(cosmic_mutations_in_top_quadrant_semi_anti_file_B_compliment)

# Calculating unique peptide promiscuities

In [ ]:
znow_bijatyka = pl.read_parquet(db_main_file)
unique_peptide_in_carmen_list = znow_bijatyka.unique("Peptide").select("Peptide")
for i in range(0,len(unique_peptide_in_carmen_list),10000):
    unique_peptide_in_carmen_list.slice(i,10000).write_parquet(temp_dir.joinpath(f"trashpanda{i}.parquet"))

In [ ]:
number_of_slices = math.ceil(len(unique_peptide_in_carmen_list)/10000)
# seq 0 10000 810000 | parallel --bar python ./calculate_promiscuity_peptides.py
for i in range(number_of_shards):
    os.system(f"python ./calculate_promiscuity_peptides.py {i}")

In [ ]:
trashpanda = pl.read_parquet(temp_dir.joinpath("bijatyka*"))
znow_bijatyka.join(trashpanda.rename({"score":"Promiscuity"}), on="Peptide").write_parquet(db_main_file, compression="zstd", compression_level=22)

# Final Cleanup

This is to clean up and delete all additional files and directories created throughout the analysis.

**Do not run the second cell unless you want to end your work here or start over.**

In [ ]:
# This is a safety code

raise KeyboardInterrupt("Are you sure you want to run the cell below?")

In [ ]:
cosmic_mutcount_per_contig_tmp.unlink()
unique_peptides_per_contig_tmp.unlink()
calculation_spam_dir.joinpath("*").unlink()
calculation_spam_dir.rmdir()
temp_dir.joinpath("*").unlink()
temp_dir.rmdir()
popcov_per_contig_file_tmp.unlink()
contig_hotspot_score_file_tmp.unlink()