# Setup

# This file requires using the environment created from environment-gtfparse.yml

In [1]:
# Imports

import polars as pl
import duckdb
from pathlib import Path
import math
import os
import numpy as np
from tqdm.notebook import tqdm

For this analysis you will need to obtain the COSMIC genome screening files as well as the COSMIC mutation classification file.
This analysis was based on the v99 release of COSMIC database
You can find the files and the license information at
https://cancer.sanger.ac.uk/cosmic/download/cosmic

In [ ]:
# Paths
project_dir = Path("/data/teamgdansk/mwaleron/carmen-analysis")

data_dir = project_dir.joinpath("data")
temp_dir = project_dir.joinpath("temp")

db_main_file = data_dir.joinpath("carmen-main.parquet")

data_subs_dir = data_dir.joinpath("subsidiary-files")
data_pub_dir = data_dir.joinpath("to-be-published")

braun_dataset_mut = data_subs_dir.joinpath("Braun_mutations_hg38_with_epitope_contigs.tsv")


contig_scaffold_list_file = data_pub_dir.joinpath("scaff_all_expanded.tsv")
contig_peptide_list_file = data_pub_dir.joinpath("contig_unique_peptide_list.tsv")
contig_hotspot_score_file = data_subs_dir.joinpath("sorted_normalized_contig_score.parquet")

main_samples_file = data_dir.joinpath("main-output-table-1.tsv")
main_samples_file_2 = data_dir.joinpath("main-output-table-2.tsv")
main_samples_file_3 = data_subs_dir.joinpath("emilia_umap_with_ids.parquet")

scaff_10_pep_hla_file = temp_dir.joinpath("Braun_hg38_pep_hla_scaff_10gw.parquet")
scaff_20_pep_hla_file = temp_dir.joinpath("Braun_hg38_pep_hla_scaff_20gw.parquet")
scaff_10_prom_file = temp_dir.joinpath("promiscuity_scaffolds_gw_of_10.csv")
scaff_20_prom_file = temp_dir.joinpath("promiscuity_scaffolds_gw_of_20.csv")

In [ ]:
contig_scaffold_list = pl.read_csv(
    contig_scaffold_list_file,
    separator='\t')
contig_peptide_list = pl.read_csv(
    contig_peptide_list_file, 
    separator='\t')

In [3]:
pep_main=pl.read_parquet(db_main_file)

In [ ]:
patient_mutations_2_hg38loo = pl.read_csv(braun_dataset_mut, separator="\t", ignore_errors=True)
patient_mutations_2_hg38loo_e = patient_mutations_2_hg38loo.with_row_index("mutid")
patient_mutations_2_hg38loo_e.write_parquet("braun_mutations_with_idx.parquet")

In [ ]:
pogo_peptides = pl.read_parquet("/data/teamgdansk/mwaleron/carmen-analysis/data/carmen-mapped-protein-annotations-pogo.parquet")

In [ ]:
peptides_in_mutations2 = duckdb.sql('''
                              select *
                              from pogo_peptides p, patient_mutations_2_hg38loo_e m
                              where (p.Chromosome = m.Chromosome)
                                 and(
                                    (m.Start_position between p.Gene_start and p.Gene_end)
                                 or (m.End_position between p.Gene_start and p.Gene_end)
                                 )                                
                                 ''')

In [ ]:
patient_peptides_in_mutations_2 = peptides_in_mutations2.pl()
patient_peptides_in_mutations_2.write_parquet("patient_peptides_in_mutations_2_before_grouping.parquet")

In [ ]:
pep_haplotype = pep_main.group_by("Peptide").agg(pl.col("Haplotype").str.split(",").explode().unique())

In [ ]:
narrow_peptides_haplotype = patient_peptides_in_mutations_2\
    .join(pep_haplotype, on="Peptide")\
    .group_by("mutid")\
    .agg(pl.col("Haplotype").explode().unique().alias("Haplotype_narrow"))\
    .with_columns(Unique_haplotypes_narrow=pl.col("Haplotype_narrow").list.len())
narrow_peptides_mut = patient_peptides_in_mutations_2\
    .group_by("mutid")\
    .agg(pl.col("Peptide").unique(), pl.col("Gene_start").min(), pl.col("Gene_end").max(), pl.col("Chromosome").last())\
    .with_columns(unique_peptides = pl.col("Peptide").list.len(), left_broad = pl.col("Gene_start")-15, right_broad = pl.col("Gene_end") + 15)

In [ ]:
narrow_peptides_mut.join(narrow_peptides_haplotype, on="mutid").rename(
    {"Peptide":"Peptide_list_narrow",
     "Gene_start":"Gene_start_narrow",
     "Gene_end":"Gene_end_narrow",
     "unique_peptides":"Unique_peptides_narrow",
     "left_broad":"Gene_start_broad",
     "right_broad":"Gene_end_broad"}
).write_parquet("narrow_mutation_wo_prom.parquet")

In [ ]:
broad_peptides_mut = duckdb.sql('''
                              select *
                              from pogo_peptides p, narrow_peptides_mut m
                              where (p.Chromosome = m.Chromosome)
                                 and(
                                    (p.Gene_start between m.left_broad and m.right_broad)
                                 or (p.Gene_end between m.left_broad and m.right_broad)
                                 )                                
                                 ''').pl()

In [ ]:
broad_peptides_haplotype = broad_peptides_mut\
    .join(pep_haplotype, on="Peptide")\
    .group_by("mutid")\
    .agg(pl.col("Haplotype").explode().unique().alias("Haplotype_broad"))\
    .with_columns(Unique_haplotypes_broad=pl.col("Haplotype_broad").list.len())

In [ ]:
broad_peptides_just_uniq = broad_peptides_mut\
    .group_by("mutid")\
    .agg(pl.col("Peptide").unique().alias("Peptide_broad"))\
    .with_columns(broad_unique_peptides = pl.col("Peptide_broad").list.len())

In [ ]:
narrow_peptides_mut.join(narrow_peptides_haplotype, on="mutid").rename(
    {"Peptide":"Peptide_list_narrow",
     "Gene_start":"Gene_start_narrow",
     "Gene_end":"Gene_end_narrow",
     "unique_peptides":"Unique_peptides_narrow",
     "left_broad":"Gene_start_broad",
     "right_broad":"Gene_end_broad"}
).join(broad_peptides_just_uniq.join(broad_peptides_haplotype, on="mutid").rename(
    {"broad_unique_peptides" : "Unique_peptides_broad"}
), on="mutid").write_parquet("narrow_and_broad_braun_mutation_wo_prom.parquet")

In [ ]:
peptides_of_10gw_scaffolds = \
    contig_scaffold_list\
        .join(
            contig_peptide_list, 
            left_on="Contigs", 
            right_on="contig")\
        .filter(pl.col("gap_width")==10)\
        .group_by("Id").agg(pl.col("pep_list").str.concat(",").str.split(","))

In [20]:
peptides_of_10gw_scaffolds\
    .explode("pep_list")\
    .join(
        pep_main.select("Peptide", "Haplotype"), 
        left_on="pep_list", 
        right_on="Peptide")\
    .with_columns(pl.col("Haplotype").str.split(","))\
    .explode("Haplotype")\
    .unique()\
    .group_by("Id")\
        .agg(pl.col("Haplotype"), pl.col("pep_list"))\
    .with_columns(
        unique_peptides=pl.col("pep_list").list.len(),
        n_unique_HLA=pl.col("Haplotype").list.len()
    ).write_parquet("Braun_hg38_pep_hla_scaff_10gw.parquet")

In [ ]:
peptides_of_20gw_scaffolds = \
    contig_scaffold_list\
        .join(
            contig_peptide_list, 
            left_on="Contigs", 
            right_on="contig")\
        .filter(pl.col("gap_width")==20)\
        .group_by("Id").agg(pl.col("pep_list").str.concat(",").str.split(","))

In [22]:
peptides_of_20gw_scaffolds\
    .explode("pep_list")\
    .join(
        pep_main.select("Peptide", "Haplotype"), 
        left_on="pep_list", 
        right_on="Peptide")\
    .with_columns(pl.col("Haplotype").str.split(","))\
    .explode("Haplotype")\
    .unique()\
    .group_by("Id")\
        .agg(pl.col("Haplotype"), pl.col("pep_list"))\
    .with_columns(
        unique_peptides=pl.col("pep_list").list.len(),
        n_unique_HLA=pl.col("Haplotype").list.len()
    ).write_parquet("Braun_hg38_pep_hla_scaff_20gw.parquet")

# Jump here

In [5]:
braun_full = pl.read_parquet(data_subs_dir.joinpath("braun_mutations_with_idx.parquet"))

In [7]:
braun_to_score = pl.read_parquet(data_subs_dir.joinpath("narrow_and_broad_braun_mutation_wo_prom.parquet"))

In [10]:
emilia_umap_with_ids = pl.read_parquet(main_samples_file_3)
xallcen = (emilia_umap_with_ids["x"].min() + emilia_umap_with_ids["x"].max() )/2
yallcen = (emilia_umap_with_ids["y"].min() + emilia_umap_with_ids["y"].max() )/2

In [11]:
def promiscuity_peptide_list(input):
    scorebase = emilia_umap_with_ids\
        .with_columns(
        scafres = pl.col("Peptides").list.set_intersection(input
        ))\
        .with_columns(alen = pl.col("scafres").list.len()).sort("alen")
    xy = scorebase.filter(pl.col("alen")>0).select("x","y")
    count = len(xy)
    if count == 0 :
        return 0
    xcen = xy["x"].sum()/count
    ycen = xy["y"].sum()/count
    lth = np.sqrt( np.power(xallcen-xcen,2) + np.power(yallcen-ycen,2))
    popcov_but_sqrt = count / math.sqrt(1+lth)
    return popcov_but_sqrt

The next parquet is produced by calcualte_immune_scorer_3.py (just run it once)

In [ ]:
braun_prom_overlap = pl.read_parquet("braun_prom_just_overlap.parquet")

In [10]:
braun_prom_overlap.mean()

shape: (1, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ mutid     ┆ Peptide_l ┆ Gene_star ┆ Gene_end_ ┆ … ┆ Haplotype ┆ Unique_ha ┆ Promiscui ┆ Promiscu │
│ ---       ┆ ist_narro ┆ t_narrow  ┆ narrow    ┆   ┆ _broad    ┆ plotypes_ ┆ ty_narrow ┆ ity_broa │
│ f64       ┆ w         ┆ ---       ┆ ---       ┆   ┆ ---       ┆ broad     ┆ ---       ┆ d        │
│           ┆ ---       ┆ f64       ┆ f64       ┆   ┆ list[str] ┆ ---       ┆ f64       ┆ ---      │
│           ┆ list[str] ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 31189.145 ┆ null      ┆ 7.1988e7  ┆ 7.1993e7  ┆ … ┆ null      ┆ 40.082525 ┆ 4.692038  ┆ 17.72858 │
│ 71        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [12]:
braun_full.join(braun_prom_overlap, on="mutid", how="left").with_columns(pl.col("Peptide_list_narrow").list.join(","), pl.col("Haplotype_narrow").list.join(","), pl.col("Peptide_broad").list.join(","), pl.col("Haplotype_broad").list.join(",")).write_csv("braun_mutations_alternative_scoring_narrow_broad.tsv", separator="\t")

/tmp/ipykernel_3688619/4168136393.py:1: DeprecationWarning: The default coalesce behavior of left join will change to `False` in the next breaking release. Pass `coalesce=True` to keep the current behavior and silence this warning.
  braun_full.join(braun_prom_overlap, on="mutid", how="left").with_columns(pl.col("Peptide_list_narrow").list.join(","), pl.col("Haplotype_narrow").list.join(","), pl.col("Peptide_broad").list.join(","), pl.col("Haplotype_broad").list.join(",")).write_csv("braun_mutations_alternative_scoring_narrow_broad.tsv", separator="\t")

This is also generated by calculate immune scorer 3

In [2]:
braun_prom_all = pl.read_parquet("braun_prom_all.parquet")

In [3]:
braun_prom_all

shape: (20_733, 33)
┌───────┬────────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬─────────┐
│ mutid ┆ Peptide_li ┆ Gene_start ┆ Gene_end_n ┆ … ┆ Tumor_alt_ ┆ gene_name  ┆ SUBJID    ┆ contig  │
│ ---   ┆ st_narrow  ┆ _narrow    ┆ arrow      ┆   ┆ count      ┆ ---        ┆ ---       ┆ ---     │
│ u32   ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---        ┆ str        ┆ str       ┆ str     │
│       ┆ list[str]  ┆ i64        ┆ i64        ┆   ┆ i64        ┆            ┆           ┆         │
╞═══════╪════════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═════════╡
│ 0     ┆ ["KEKEDVPV ┆ 52579172   ┆ 52586427   ┆ … ┆ 53         ┆ PBRM1      ┆ RCC_15    ┆ C48753  │
│       ┆ EM"]       ┆            ┆            ┆   ┆            ┆            ┆           ┆         │
│ 1     ┆ ["RRLDIVRS ┆ 10149842   ┆ 10149881   ┆ … ┆ 43         ┆ VHL        ┆ RCC25-732 ┆ C43929  │
│       ┆ LYE", "RRL ┆            ┆            ┆   ┆            ┆            ┆           ┆         │
│       ┆ DIVRSLY",  ┆            ┆            ┆   ┆            ┆            ┆           ┆         │
│       ┆ …          ┆            ┆            ┆   ┆            ┆            ┆           ┆         │
│ 2     ┆ ["SREPSQVI ┆ 10142048   ┆ 10142075   ┆ … ┆ 101        ┆ VHL        ┆ RCC25-535 ┆ C43924  │
│       ┆ F"]        ┆            ┆            ┆   ┆            ┆            ┆           ┆         │
│ 6     ┆ ["QVLEGHVL ┆ 38074866   ┆ 38074899   ┆ … ┆ 14         ┆ CYP1B1     ┆ RCC25-345 ┆ C28244  │
│       ┆ SEA"]      ┆            ┆            ┆   ┆            ┆            ┆           ┆         │
│ 7     ┆ ["LAAAVHKE ┆ 53201600   ┆ 53201627   ┆ … ┆ 31         ┆ KDM5C      ┆ RCC25-486 ┆ C242184 │
│       ┆ M"]        ┆            ┆            ┆   ┆            ┆            ┆           ┆         │
│ …     ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …       │
│ 62640 ┆ ["VSRIKENG ┆ 70388505   ┆ 70388541   ┆ … ┆ 58         ┆ SYNJ2BP    ┆ RCC25-116 ┆ C167583 │
│       ┆ AAAL", "SR ┆            ┆            ┆   ┆            ┆            ┆           ┆         │
│       ┆ IKENGAAAL" ┆            ┆            ┆   ┆            ┆            ┆           ┆         │
│       ┆ …          ┆            ┆            ┆   ┆            ┆            ┆           ┆         │
│ 62645 ┆ ["ILPKKSWH ┆ 54159662   ┆ 54159689   ┆ … ┆ 18         ┆ TMC4       ┆ RCC25-931 ┆ C223532 │
│       ┆ V"]        ┆            ┆            ┆   ┆            ┆            ┆           ┆         │
│ 62656 ┆ ["VATGVIST ┆ 66089656   ┆ 66089692   ┆ … ┆ 4          ┆ AC068533.7 ┆ RCC25-284 ┆ C95434  │
│       ┆ L", "VLQVA ┆            ┆            ┆   ┆            ┆            ┆           ┆         │
│       ┆ TGVIST"]   ┆            ┆            ┆   ┆            ┆            ┆           ┆         │
│ 62657 ┆ ["APPESRVS ┆ 37011029   ┆ 37011074   ┆ … ┆ 46         ┆ TST        ┆ RCC25-3   ┆ C236743 │
│       ┆ QGKSEKA"]  ┆            ┆            ┆   ┆            ┆            ┆           ┆         │
│ 62658 ┆ ["QETRMVAL ┆ 38733338   ┆ 38733362   ┆ … ┆ 17         ┆ CISD3      ┆ RCC25-659 ┆ C197033 │
│       ┆ "]         ┆            ┆            ┆   ┆            ┆            ┆           ┆         │
└───────┴────────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴─────────┘

# scaffold scoring

These parquet files are generated in step 11 by calculate_immune_scorer.py and calculate_immune_scorer_2.py respetively.

In [22]:
scaffold10_scores = pl.scan_parquet("/data/teamgdansk/mwaleron/carmen-analysis/temp/parquetspam/rescored_scaf10_slice_*.parquet")

In [ ]:
scaffold10_scores.sort("Id").drop("pep_list").sink_csv(scaff_10_prom_file)

In [7]:
scaffold20_scores = pl.scan_parquet("/data/teamgdansk/mwaleron/carmen-analysis/temp/parquetspam/rescored_scaf20_slice_*.parquet")

In [ ]:
scaffold20_scores.sort("Id").drop("pep_list").sink_csv(scaff_20_prom_file)

In [13]:
braunmut = pl.read_csv(braun_dataset_mut, separator="\t", ignore_errors=True)

In [8]:
braunmut = pl.read_parquet(data_subs_dir.joinpath("braun_mutations_with_idx.parquet"))

In [20]:
braunmut

shape: (62_659, 17)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬─────────┐
│ Sample_ID  ┆ Chromosom ┆ Start_pos ┆ End_posit ┆ … ┆ Tumor_alt ┆ gene_name ┆ SUBJID    ┆ contig  │
│ ---        ┆ e         ┆ ition     ┆ ion       ┆   ┆ _count    ┆ ---       ┆ ---       ┆ ---     │
│ str        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ str     │
│            ┆ str       ┆ i64       ┆ i64       ┆   ┆ i64       ┆           ┆           ┆         │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═════════╡
│ RCC_15-Tum ┆ 3         ┆ 52579179  ┆ 52579179  ┆ … ┆ 53        ┆ PBRM1     ┆ RCC_15    ┆ C48753  │
│ or-SM-A46E ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
│ E          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
│ EA698866   ┆ 3         ┆ 10149856  ┆ 10149856  ┆ … ┆ 43        ┆ VHL       ┆ RCC25-732 ┆ C43929  │
│ EA698881   ┆ 3         ┆ 10142055  ┆ 10142055  ┆ … ┆ 101       ┆ VHL       ┆ RCC25-535 ┆ C43924  │
│ EA700340   ┆ 3         ┆ 10149807  ┆ 10149807  ┆ … ┆ 7         ┆ VHL       ┆ RCC25-181 ┆ null    │
│ RCC_52-Tum ┆ 2         ┆ 178632229 ┆ 178632229 ┆ … ┆ 23        ┆ TTN       ┆ RCC_52    ┆ null    │
│ or-SM-A46E ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
│ U          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …       │
│ EA700525   ┆ 6         ┆ 155314319 ┆ 155314319 ┆ … ┆ 40        ┆ TFB1M     ┆ RCC25-915 ┆ null    │
│ EA700647   ┆ 16        ┆ 696895    ┆ 696899    ┆ … ┆ 41        ┆ FBXL16    ┆ RCC25-671 ┆ null    │
│ EA700541   ┆ 7         ┆ 66089677  ┆ 66089677  ┆ … ┆ 4         ┆ AC068533. ┆ RCC25-284 ┆ C95434  │
│            ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆           ┆         │
│ EA700559   ┆ 22        ┆ 37011066  ┆ 37011067  ┆ … ┆ 46        ┆ TST       ┆ RCC25-3   ┆ C236743 │
│ EA700616   ┆ 17        ┆ 38733350  ┆ 38733350  ┆ … ┆ 17        ┆ CISD3     ┆ RCC25-659 ┆ C197033 │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴─────────┘

In [9]:
braunmut_scaffold10 = duckdb.sql('''
                                 select * 
                                 from braunmut b, scaff10 c
                                 where c.Chromosome = b.Chromosome
                                 and(
                                     (b.Start_position between c.Gene_start and c.Gene_end)
                                   or(b.End_position between c.Gene_start and c.Gene_end)
                                 )
                                 ''').pl()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [11]:
braunmut_scaffold10.write_csv("Braun_hg38_mutations_in_scaffolds_10gw.csv")

In [32]:
braunmut_scaffold10.select(pl.len())

shape: (1, 1)
┌───────┐
│ len   │
│ ---   │
│ u32   │
╞═══════╡
│ 20638 │
└───────┘

In [31]:
braunmut_scaffold10.group_by(["Sample_ID", "Chromosome", "Start_position", "Id"]).agg(pl.all())

shape: (20_638, 23)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Sample_ID ┆ Chromosom ┆ Start_pos ┆ Id        ┆ … ┆ Gene_star ┆ Gene_end  ┆ Multi_con ┆ gap_widt │
│ ---       ┆ e         ┆ ition     ┆ ---       ┆   ┆ t         ┆ ---       ┆ tig       ┆ h        │
│ str       ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ list[i64] ┆ ---       ┆ ---      │
│           ┆ str       ┆ i64       ┆           ┆   ┆ list[i64] ┆           ┆ list[str] ┆ list[i64 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ]        │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ EA700252  ┆ 1         ┆ 218405195 ┆ S_10_1867 ┆ … ┆ [21836341 ┆ [21840521 ┆ ["N"]     ┆ [10]     │
│           ┆           ┆           ┆ 3         ┆   ┆ 1]        ┆ 8]        ┆           ┆          │
│ EA699820  ┆ 3         ┆ 49373315  ┆ S_10_3952 ┆ … ┆ [49360323 ┆ [49375520 ┆ ["N"]     ┆ [10]     │
│           ┆           ┆           ┆ 0         ┆   ┆ ]         ┆ ]         ┆           ┆          │
│ EA699642  ┆ 14        ┆ 63283169  ┆ S_10_1389 ┆ … ┆ [63283163 ┆ [63283189 ┆ ["N"]     ┆ [10]     │
│           ┆           ┆           ┆ 77        ┆   ┆ ]         ┆ ]         ┆           ┆          │
│ EA698479  ┆ 2         ┆ 159186856 ┆ S_10_2994 ┆ … ┆ [15918582 ┆ [15918695 ┆ ["Y"]     ┆ [10]     │
│           ┆           ┆           ┆ 6         ┆   ┆ 2]        ┆ 2]        ┆           ┆          │
│ EA698908  ┆ 11        ┆ 61908090  ┆ S_10_1141 ┆ … ┆ [61907604 ┆ [61908110 ┆ ["Y"]     ┆ [10]     │
│           ┆           ┆           ┆ 18        ┆   ┆ ]         ┆ ]         ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ EA698359  ┆ 12        ┆ 14542121  ┆ S_10_1224 ┆ … ┆ [14540881 ┆ [14542218 ┆ ["N"]     ┆ [10]     │
│           ┆           ┆           ┆ 58        ┆   ┆ ]         ┆ ]         ┆           ┆          │
│ EA699724  ┆ 15        ┆ 78490646  ┆ S_10_1483 ┆ … ┆ [78490625 ┆ [78490672 ┆ ["N"]     ┆ [10]     │
│           ┆           ┆           ┆ 30        ┆   ┆ ]         ┆ ]         ┆           ┆          │
│ EA699911  ┆ 17        ┆ 7823961   ┆ S_10_1606 ┆ … ┆ [7823950] ┆ [7823976] ┆ ["N"]     ┆ [10]     │
│           ┆           ┆           ┆ 77        ┆   ┆           ┆           ┆           ┆          │
│ RCC_15-Tu ┆ 2         ┆ 241239672 ┆ S_10_3577 ┆ … ┆ [24123873 ┆ [24123974 ┆ ["Y"]     ┆ [10]     │
│ mor-SM-A4 ┆           ┆           ┆ 4         ┆   ┆ 1]        ┆ 8]        ┆           ┆          │
│ 6EE       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ EA700628  ┆ 16        ┆ 58519006  ┆ S_10_1558 ┆ … ┆ [58518955 ┆ [58519011 ┆ ["N"]     ┆ [10]     │
│           ┆           ┆           ┆ 16        ┆   ┆ ]         ┆ ]         ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [23]:
braunmut_scaffold10 = pl.read_csv("Braun_hg38_mutations_in_scaffolds_10gw.csv")
braunmut_scaffold20 = pl.read_csv("Braun_hg38_mutations_in_scaffolds_20gw.csv")

In [14]:
braunpephla_scaffold10 = pl.read_parquet("Braun_hg38_pep_hla_scaff_10gw.parquet")
braunpephla_scaffold20 = pl.read_parquet("Braun_hg38_pep_hla_scaff_20gw.parquet")

In [ ]:
scaf10prom = pl.read_csv(scaff_10_prom_file)
scaf20prom = pl.read_csv("promiscuity_scaffolds_gw_of_20.csv")

In [27]:
scaf10prom

shape: (207_137, 5)
┌────────────┬─────────────────┬──────────────────┬──────────────────┬──────────────────┐
│ Id         ┆ popcov_but_sqrt ┆ popcov_but_sqrt2 ┆ popcov_but_sqrt3 ┆ popcov_but_sqrt4 │
│ ---        ┆ ---             ┆ ---              ┆ ---              ┆ ---              │
│ str        ┆ f64             ┆ f64              ┆ f64              ┆ f64              │
╞════════════╪═════════════════╪══════════════════╪══════════════════╪══════════════════╡
│ S_10_1     ┆ 0.510925        ┆ 0.0              ┆ 0.0              ┆ 0.0              │
│ S_10_10    ┆ 0.0             ┆ 0.0              ┆ 0.0              ┆ 0.0              │
│ S_10_100   ┆ 0.0             ┆ 0.0              ┆ 0.0              ┆ 0.0              │
│ S_10_1000  ┆ 0.376947        ┆ 0.0              ┆ 0.0              ┆ 0.0              │
│ S_10_10000 ┆ 2.281           ┆ 0.0              ┆ 0.0              ┆ 0.0              │
│ …          ┆ …               ┆ …                ┆ …                ┆ …                │
│ S_10_99995 ┆ 12.144016       ┆ 0.0              ┆ 0.0              ┆ 0.0              │
│ S_10_99996 ┆ 12.836341       ┆ 0.0              ┆ 0.0              ┆ 0.0              │
│ S_10_99997 ┆ 1.439115        ┆ 0.0              ┆ 0.0              ┆ 0.0              │
│ S_10_99998 ┆ 8.468909        ┆ 0.0              ┆ 0.0              ┆ 0.0              │
│ S_10_99999 ┆ 0.0             ┆ 0.0              ┆ 0.0              ┆ 0.0              │
└────────────┴─────────────────┴──────────────────┴──────────────────┴──────────────────┘

In [35]:
braunmut_scaffold20

shape: (21_151, 24)
┌───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ mutid ┆ Sample_ID  ┆ Chromosome ┆ Start_posi ┆ … ┆ Gene_star ┆ Gene_end  ┆ Multi_con ┆ gap_width │
│ ---   ┆ ---        ┆ ---        ┆ tion       ┆   ┆ t         ┆ ---       ┆ tig       ┆ ---       │
│ u32   ┆ str        ┆ str        ┆ ---        ┆   ┆ ---       ┆ i64       ┆ ---       ┆ i64       │
│       ┆            ┆            ┆ i64        ┆   ┆ i64       ┆           ┆ str       ┆           │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 62228 ┆ EA700350   ┆ 4          ┆ 142314840  ┆ … ┆ 142314742 ┆ 142402946 ┆ N         ┆ 20        │
│ 62506 ┆ EA698327   ┆ 19         ┆ 57844252   ┆ … ┆ 57819925  ┆ 57856142  ┆ N         ┆ 20        │
│ 62213 ┆ RP-1458_RC ┆ 19         ┆ 17191105   ┆ … ┆ 17191103  ┆ 17192913  ┆ Y         ┆ 20        │
│       ┆ CBMS-00153 ┆            ┆            ┆   ┆           ┆           ┆           ┆           │
│       ┆ -T_v4_Exom ┆            ┆            ┆   ┆           ┆           ┆           ┆           │
│       ┆ …          ┆            ┆            ┆   ┆           ┆           ┆           ┆           │
│ 60018 ┆ EA699646   ┆ 18         ┆ 12971255   ┆ … ┆ 12971211  ┆ 12978776  ┆ N         ┆ 20        │
│ 61726 ┆ EA699807   ┆ 3          ┆ 10142115   ┆ … ┆ 10142010  ┆ 10142120  ┆ Y         ┆ 20        │
│ …     ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2889  ┆ EA699824   ┆ 1          ┆ 11124535   ┆ … ┆ 11122114  ┆ 11126721  ┆ Y         ┆ 20        │
│ 2693  ┆ EA700001   ┆ 1          ┆ 246903941  ┆ … ┆ 246902664 ┆ 246903966 ┆ N         ┆ 20        │
│ 2162  ┆ EA700559   ┆ 1          ┆ 18875499   ┆ … ┆ 18875414  ┆ 18876356  ┆ N         ┆ 20        │
│ 1175  ┆ EA698355   ┆ 1          ┆ 161525091  ┆ … ┆ 161524998 ┆ 161525138 ┆ Y         ┆ 20        │
│ 983   ┆ EA700545   ┆ 1          ┆ 11124501   ┆ … ┆ 11122114  ┆ 11126721  ┆ Y         ┆ 20        │
└───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [18]:
braunmut_scaffold10.join(braunpephla_scaffold10, on="Id")

shape: (20_638, 28)
┌───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ mutid ┆ Sample_ID  ┆ Chromosome ┆ Start_posi ┆ … ┆ Haplotype ┆ pep_list  ┆ unique_pe ┆ n_unique_ │
│ ---   ┆ ---        ┆ ---        ┆ tion       ┆   ┆ ---       ┆ ---       ┆ ptides    ┆ HLA       │
│ u32   ┆ str        ┆ str        ┆ ---        ┆   ┆ list[str] ┆ list[str] ┆ ---       ┆ ---       │
│       ┆            ┆            ┆ i64        ┆   ┆           ┆           ┆ u32       ┆ u32       │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 55176 ┆ EA700375   ┆ 9          ┆ 75133306   ┆ … ┆ ["A*02:01 ┆ ["ESIDNPL ┆ 60        ┆ 60        │
│       ┆            ┆            ┆            ┆   ┆ ", "B*40: ┆ HEAAKR",  ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆ 02", …    ┆ "AESIDNPL ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆ "A*02…    ┆ HEA…      ┆           ┆           │
│ 45160 ┆ EA699811   ┆ 20         ┆ 4699615    ┆ … ┆ ["A*23:01 ┆ ["HRYPNQV ┆ 213       ┆ 213       │
│       ┆            ┆            ┆            ┆   ┆ ", "A*24: ┆ YY", "AVV ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆ 02", …    ┆ GGLGGY",  ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆ "B*13…    ┆ … "…      ┆           ┆           │
│ 1129  ┆ RP-1458_RC ┆ 16         ┆ 67882496   ┆ … ┆ ["A*32:01 ┆ ["REAFQSV ┆ 74        ┆ 74        │
│       ┆ CBMS-00119 ┆            ┆            ┆   ┆ ", "B*07: ┆ VL", "LQG ┆           ┆           │
│       ┆ -T_v2_Exom ┆            ┆            ┆   ┆ 02", …    ┆ PMQAAY",  ┆           ┆           │
│       ┆ …          ┆            ┆            ┆   ┆ "C*03…    ┆ … "…      ┆           ┆           │
│ 16279 ┆ EA699745   ┆ 7          ┆ 985018     ┆ … ┆ ["B*40:01 ┆ ["FTVRALH ┆ 14        ┆ 14        │
│       ┆            ┆            ┆            ┆   ┆ ", "A*29: ┆ SL", "FTV ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆ 02", …    ┆ RALHSL",  ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆ "A*32…    ┆ … "…      ┆           ┆           │
│ 54440 ┆ EA700159   ┆ 16         ┆ 84659928   ┆ … ┆ ["B*27:05 ┆ ["SYVAGLP ┆ 108       ┆ 108       │
│       ┆            ┆            ┆            ┆   ┆ ", "A*32: ┆ RF", "YVA ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆ 01", …    ┆ GLPRFTY", ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆ "B*07…    ┆ … …       ┆           ┆           │
│ …     ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 58102 ┆ RP-1458_RC ┆ 16         ┆ 70571730   ┆ … ┆ ["B*15:01 ┆ ["KLEDIRT ┆ 171       ┆ 171       │
│       ┆ CBMS-00136 ┆            ┆            ┆   ┆ ", "A*02: ┆ RY", "DIR ┆           ┆           │
│       ┆ -T_v1_Exom ┆            ┆            ┆   ┆ 06", …    ┆ TRYAF", … ┆           ┆           │
│       ┆ …          ┆            ┆            ┆   ┆ "A*01…    ┆ "D…       ┆           ┆           │
│ 57063 ┆ EA700520   ┆ 15         ┆ 28213809   ┆ … ┆ ["A*03:01 ┆ ["TPKGKIT ┆ 8         ┆ 8         │
│       ┆            ┆            ┆            ┆   ┆ ", "B*08: ┆ V", "TPKG ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆ 01", …    ┆ KITV", …  ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆ null]     ┆ "GT…      ┆           ┆           │
│ 40721 ┆ EA699821   ┆ 2          ┆ 219418719  ┆ … ┆ ["A*30:01 ┆ ["SLADAVN ┆ 2682      ┆ 2682      │
│       ┆            ┆            ┆            ┆   ┆ ", "C*02: ┆ QEF", "AL ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆ 02", …    ┆ AAEVNRL", ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆ "B*49…    ┆ … …       ┆           ┆           │
│ 38889 ┆ EA700452   ┆ 2          ┆ 219420290  ┆ … ┆ ["A*30:01 ┆ ["SLADAVN ┆ 2682      ┆ 2682      │
│       ┆            ┆            ┆            ┆   ┆ ", "C*02: ┆ QEF", "AL ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆ 02", …    ┆ AAEVNRL", ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆ "B*49…    ┆ … …       ┆           ┆           │
│ 31437 ┆ EA700199   ┆ 2          ┆ 219421384  ┆ … ┆ ["A*30:01 ┆ ["SLADAVN ┆ 2682      ┆ 2682      │
│       ┆            ┆            ┆            ┆   ┆ ", "C*02: ┆ QEF", "AL ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆ 02", …    ┆ AAEVNRL", ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆ "B*49…    ┆ … …       ┆           ┆           │
└───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [21]:
scaf10prom

shape: (94_000, 5)
┌─────────────┬─────────────────┬──────────────────┬──────────────────┬──────────────────┐
│ Id          ┆ popcov_but_sqrt ┆ popcov_but_sqrt2 ┆ popcov_but_sqrt3 ┆ popcov_but_sqrt4 │
│ ---         ┆ ---             ┆ ---              ┆ ---              ┆ ---              │
│ str         ┆ f64             ┆ f64              ┆ f64              ┆ f64              │
╞═════════════╪═════════════════╪══════════════════╪══════════════════╪══════════════════╡
│ S_10_100    ┆ 0.0             ┆ 0.0              ┆ 0.0              ┆ 0.0              │
│ S_10_1000   ┆ 0.376947        ┆ 0.0              ┆ 0.0              ┆ 0.0              │
│ S_10_100000 ┆ 0.57704         ┆ 0.0              ┆ 0.0              ┆ 0.0              │
│ S_10_100002 ┆ 61.040115       ┆ 0.729108         ┆ 0.0              ┆ 0.0              │
│ S_10_100003 ┆ 1.08112         ┆ 0.0              ┆ 0.0              ┆ 0.0              │
│ …           ┆ …               ┆ …                ┆ …                ┆ …                │
│ S_10_99987  ┆ 17.539472       ┆ 0.0              ┆ 0.0              ┆ 0.0              │
│ S_10_99988  ┆ 0.373833        ┆ 0.0              ┆ 0.0              ┆ 0.0              │
│ S_10_99989  ┆ 0.999627        ┆ 0.0              ┆ 0.0              ┆ 0.0              │
│ S_10_99995  ┆ 12.144016       ┆ 0.0              ┆ 0.0              ┆ 0.0              │
│ S_10_99997  ┆ 1.439115        ┆ 0.0              ┆ 0.0              ┆ 0.0              │
└─────────────┴─────────────────┴──────────────────┴──────────────────┴──────────────────┘

In [31]:
braunmut.join(braunmut_scaffold10.join(braunpephla_scaffold10, on="Id").drop(["Haplotype", "pep_list"]).join(scaf10prom, on="Id"), on="mutid", how="left").write_csv("Braun_hg38_epscaff10_w_score_2025.tsv", separator="\t")

/tmp/ipykernel_520103/2034034041.py:1: DeprecationWarning: The default coalesce behavior of left join will change to `False` in the next breaking release. Pass `coalesce=True` to keep the current behavior and silence this warning.
  braunmut.join(braunmut_scaffold10.join(braunpephla_scaffold10, on="Id").drop(["Haplotype", "pep_list"]).join(scaf10prom, on="Id"), on="mutid", how="left").write_csv("Braun_hg38_epscaff10_w_score_2025.tsv", separator="\t")

In [36]:
braunmut.join(braunmut_scaffold20.join(braunpephla_scaffold20, on="Id").drop(["Haplotype", "pep_list"]).join(scaf20prom, on="Id"), on="mutid", how="left").write_csv("Braun_hg38_epscaff20_w_score_2025.tsv", separator="\t")

/tmp/ipykernel_520103/4088974471.py:1: DeprecationWarning: The default coalesce behavior of left join will change to `False` in the next breaking release. Pass `coalesce=True` to keep the current behavior and silence this warning.
  braunmut.join(braunmut_scaffold20.join(braunpephla_scaffold20, on="Id").drop(["Haplotype", "pep_list"]).join(scaf20prom, on="Id"), on="mutid", how="left").write_csv("Braun_hg38_epscaff20_w_score_2025.tsv", separator="\t")

# TODO i don't think the rest is necessary anymore

In [39]:
braunmut_scaffold10.join(braunpephla_scaffold10, on="Id").drop(["Haplotype", "pep_list"]).join(scaf10prom, on="Id").write_csv("Braun_hg38_epscaff10_w_score.tsv", separator="\t")

In [40]:
braunmut_scaffold20.join(braunpephla_scaffold20, on="Id").drop(["Haplotype", "pep_list"]).join(scaf20prom, on="Id").write_csv("Braun_hg38_epscaff20_w_score.tsv", separator="\t")

In [6]:
scaff10 = contig_scaffold_list.filter(pl.col("gap_width")==10).drop("Contigs").unique().with_columns(pl.col("Chromosome").str.strip_chars_start("chr"))

In [7]:
scaff20 = contig_scaffold_list.filter(pl.col("gap_width")==20).drop("Contigs").unique().with_columns(pl.col("Chromosome").str.strip_chars_start("chr"))

In [12]:
braunmut_scaffold20 = duckdb.sql('''
                                 select * 
                                 from braunmut b, scaff20 c
                                 where c.Chromosome = b.Chromosome
                                 and(
                                     (b.Start_position between c.Gene_start and c.Gene_end)
                                   or(b.End_position between c.Gene_start and c.Gene_end)
                                 )
                                 ''').pl()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [13]:
braunmut_scaffold20.write_csv("Braun_hg38_mutations_in_scaffolds_20gw.csv")

In [29]:
braunmut_scaffold20

shape: (21_151, 23)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Sample_ID ┆ Chromosom ┆ Start_pos ┆ End_posit ┆ … ┆ Gene_star ┆ Gene_end  ┆ Multi_con ┆ gap_widt │
│ ---       ┆ e         ┆ ition     ┆ ion       ┆   ┆ t         ┆ ---       ┆ tig       ┆ h        │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ i64       ┆ ---       ┆ ---      │
│           ┆ str       ┆ i64       ┆ i64       ┆   ┆ i64       ┆           ┆ str       ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ EA700354  ┆ X         ┆ 49251615  ┆ 49251615  ┆ … ┆ 49251436  ┆ 49251675  ┆ Y         ┆ 20       │
│ EA699702  ┆ 12        ┆ 6937305   ┆ 6937305   ┆ … ┆ 6937290   ┆ 6937325   ┆ N         ┆ 20       │
│ EA698476  ┆ 1         ┆ 22908007  ┆ 22908007  ┆ … ┆ 22907986  ┆ 22908012  ┆ N         ┆ 20       │
│ EA700455  ┆ 2         ┆ 151642690 ┆ 151642690 ┆ … ┆ 151642667 ┆ 151642776 ┆ N         ┆ 20       │
│ EA698900  ┆ 14        ┆ 77026709  ┆ 77026709  ┆ … ┆ 77026647  ┆ 77026769  ┆ Y         ┆ 20       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ EA698477  ┆ 19        ┆ 44781224  ┆ 44781224  ┆ … ┆ 44781214  ┆ 44781240  ┆ N         ┆ 20       │
│ EA699646  ┆ 19        ┆ 5667839   ┆ 5667839   ┆ … ┆ 5667378   ┆ 5667866   ┆ Y         ┆ 20       │
│ EA699646  ┆ 1         ┆ 204443421 ┆ 204443421 ┆ … ┆ 204442586 ┆ 204443470 ┆ N         ┆ 20       │
│ EA699728  ┆ 1         ┆ 77935871  ┆ 77935871  ┆ … ┆ 77933435  ┆ 77935882  ┆ N         ┆ 20       │
│ RP-1458_R ┆ 1         ┆ 154964292 ┆ 154964292 ┆ … ┆ 154964276 ┆ 154964302 ┆ N         ┆ 20       │
│ CCBMS-000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 74-T_v4_E ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ xom…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘